name: prism_flutter
description: Flutter extensions for the Prism color library. Conversion between Ray and Flutter Color objects with palette support.
version: 2.0.0-beta.1
repository: https://github.com/jimmyff/prism
website: https://github.com/jimmyff/prism/packages/prism_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  prism: ^2.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# dependency_overrides:
#   prism:
#     path: ../prism
