name: prism_flutter
description: Flutter extensions for the Prism color manipulation library. Seamless conversion between Ray and Flutter Color objects.
version: 1.0.1
repository: https://github.com/jimmyff/prism
website: https://github.com/jimmyff/prism/packages/prism_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  prism: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
