name: prism
description: An optimized, zero zero-dependency color manipulation library for Dart & Flutter with multiple color models, accessibility tools, and pre-built palettes.
version: 2.0.0-beta.1
repository: https://github.com/jimmyff/prism
website: https://github.com/jimmyff/prism/packages/prism

environment:
  sdk: '>=3.3.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: any
  test: any
  path: any

  image: any # for generating the gallery
