name: prism
description: A powerful and efficient color manipulation library for Dart and Flutter applications. Features Ray class, RayScheme accessibility tools, and extensive color palettes.
version: 2.0.0-alpha.4
repository: https://github.com/jimmyff/prism
website: https://github.com/jimmyff/prism/packages/prism

environment:
  sdk: '>=3.3.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: any
  test: any
  path: any

  image: any # for generating the gallery
