name: prism
description: A powerful and efficient color manipulation library for Dart and Flutter applications. Work with colors through the Ray class.
version: 1.0.0
repository: https://github.com/jimmyff/prism
website: https://github.com/jimmyff/prism/packages/prism

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: any
  test: any
